# Generated by Django 5.0 on 2024-11-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_tenant_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.unit'),
        ),
    ]
