# Generated by Django 5.0 on 2024-11-21 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_tenant_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantInvoice',
            new_name='UserInvoice',
        ),
        migrations.AlterField(
            model_name='userinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
