# Generated by Django 5.0 on 2024-11-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_tenantinvoice_userinvoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvoice',
            old_name='tenant',
            new_name='user',
        ),
    ]
