# Generated by Django 5.0 on 2024-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_landlordprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='pending_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='total_billed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
