# Generated by Django 5.0 on 2024-10-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_landlordprofile_pending_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeeinvoice',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.landlordprofile'),
        ),
    ]
