# Generated by Django 5.0 on 2024-10-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_servicefeeinvoice_landlord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.landlordprofile')),
            ],
        ),
    ]
