# Generated by Django 5.0 on 2024-10-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_specialinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/special/'),
        ),
    ]
