# Generated by Django 5.0 on 2024-10-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_maintenancerequest_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='maintenance-requests/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='rentinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
