# Generated by Django 5.0 on 2024-10-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_maintenancerequest_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='house',
            new_name='unit',
        ),
    ]
