# Generated by Django 5.0 on 2024-10-06 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_location_property_estate_rentsinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='rentsinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='waterbillinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
