# Generated by Django 5.0 on 2024-10-07 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_property_bathrooms_remove_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentinvoice',
            options={},
        ),
        migrations.RenameField(
            model_name='rentinvoice',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='rentinvoice',
            old_name='billing_period_start',
            new_name='issued_date',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='arrears',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='billing_period_end',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='current_water_reading',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='previous_water_reading',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='reading_date',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='water_bill',
        ),
        migrations.RemoveField(
            model_name='rentinvoice',
            name='water_consumption',
        ),
        migrations.AddField(
            model_name='rentinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentinvoice',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tenantprofile'),
        ),
        migrations.AddField(
            model_name='servicefeeinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/service-fee/'),
        ),
        migrations.AlterField(
            model_name='rentinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/rent/'),
        ),
        migrations.AlterField(
            model_name='rentinvoice',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.property'),
        ),
        migrations.AlterField(
            model_name='servicefeeinvoice',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterbillinvoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/waterbill/'),
        ),
        migrations.AlterField(
            model_name='waterbillinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tenantprofile'),
        ),
        migrations.DeleteModel(
            name='RentsInvoice',
        ),
    ]
