# Generated by Django 5.0 on 2024-10-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_rentinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='water_meter_present',
            field=models.BooleanField(default=True),
        ),
    ]
